### ISSUE TITLE
Quotes Without Authors

### ISSUE THREAD

**Issue by amcnulty** [edobb/quote-book#17]
Some random quotes that are generated from the API do not have authors. When this is the case there is nothing displayed in the author section. If users save these quotes there will be nothing to put in the database for the author field. This is not a desired behavior. There should be some conditional that checks if author is blank from the API and set the author to "Author Unknown" or something similar. This way users are not confused as to why the quote they just looked up has no author.

**Comment by ernie45** [comment]
Quotes without a given author will save the author as "Unknown Author"
