### ISSUE TITLE
Prevent duplicate quotes

### ISSUE THREAD

**Issue by amcnulty** [edobb/quote-book#4]
Duplicate quotes should not be allowed in the database. This function should work by searching for matches to the quote and not the author. Duplicate quotes with different authors should not be allowed.

**Comment by ernie45** [comment]
The application now checks if a current quote to add already exists in the database. If it exists, the user cannot input the quote. If the quote doesn't yet exist, the user can add the quote into our database- that includes the custom quote as well as the random quote to save.
